"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, Bell, BrainCircuit, Check, ChevronRight, CircleAlert, Clock3, Eye, LineChart, RotateCcw, SlidersHorizontal, Sparkles, Target, Zap } from "lucide-react";
import { useRouter } from "next/navigation";
import StockSearch from "@/components/stock-search";
import SmartPilotDrawer from "@/components/smartpilot-drawer";
import MarketStatusBar from "@/components/market-status-bar";
import { useMarketIntelligence } from "@/hooks/use-market-intelligence";

type Page = "changes" | "market-map" | "smartpilot" | "what-if" | "replay" | "portfolio" | "goals" | "patterns" | "alerts";
const titles: Record<Page, [string, string, string]> = {
  changes: ["ATTENTION ENGINE", "Smart changes", "What meaningfully changed?"],
  "market-map": ["MARKET TOPOLOGY", "Market map", "Where is the market moving right now?"],
  smartpilot: ["INTELLIGENCE LAYER", "SmartPilot", "Why is it happening?"],
  "what-if": ["SIMULATION LAB", "What-if lab", "What could happen under different scenarios?"],
  replay: ["CHANGE HISTORY", "Change replay", "How did this change develop?"],
  portfolio: ["PERSONAL RELEVANCE", "Portfolio intelligence", "How does the market affect my holdings?"],
  goals: ["GOAL INTELLIGENCE", "Goals", "Is this activity relevant to your goals?"],
  patterns: ["BEHAVIORAL INTELLIGENCE", "Patterns", "What does SmartPilot learn from repeated behavior?"],
  alerts: ["ATTENTION SETTINGS", "Alerts", "When should SmartPilot bring a change back to you?"],
};

export default function InteractiveFeaturePage({ page }: { page: Page }) {
  const router = useRouter();
  const { data, loading, refresh } = useMarketIntelligence();
  const [pilotOpen, setPilotOpen] = useState(false);
  const [selectedSymbol, setSelectedSymbol] = useState("");
  const [filter, setFilter] = useState("ALL");
  const [scenario, setScenario] = useState(-5);
  const [replay, setReplay] = useState(100);
  const [goal, setGoal] = useState("LONG-TERM GROWTH");
  const [alerts, setAlerts] = useState(() => [true, true, true]);
  const quotes = data?.quotes || [];
  const changes = data?.changes || [];
  const selected = quotes.find((quote) => quote.symbol === selectedSymbol) || quotes[0];
  const filteredChanges = useMemo(() => filter === "ALL" ? changes : changes.filter((change) => filter === "UNUSUAL" ? change.score >= 60 : change.summary.toUpperCase().includes(filter)), [changes, filter]);
  const [eyebrow, title, question] = titles[page];
  const logout = async () => { await fetch("/api/auth/session", { method: "DELETE" }); router.replace("/login"); };

  return <main className="feature-shell"><header className="feature-topbar"><button className="back-button" onClick={() => router.push("/dashboard")}><ArrowLeft size={17} /> Overview</button><StockSearch /><div className="feature-top-actions"><button className="feature-pilot" onClick={() => setPilotOpen(true)}><span className="pilot-fab-orb"><BrainCircuit size={16} /></span><span>Ask SmartPilot</span></button><button className="icon-button" onClick={logout} aria-label="Log out" title="Log out">↪</button></div></header><MarketStatusBar data={data} loading={loading} onRefresh={() => void refresh()} /><section className="feature-content"><div className="feature-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{question}</p></div><div className="feature-icon"><LineChart size={25} /></div></div><div className="feature-workbench">{page === "changes" && <ChangesView changes={filteredChanges} filter={filter} setFilter={setFilter} onSelect={setSelectedSymbol} />}{page === "market-map" && <MapView quotes={quotes} changes={changes} selected={selectedSymbol} onSelect={setSelectedSymbol} />}{page === "smartpilot" && <SmartPilotView changes={changes} onOpen={() => setPilotOpen(true)} />}{page === "what-if" && <WhatIfView quote={selected} scenario={scenario} setScenario={setScenario} />}{page === "replay" && <ReplayView quote={selected} progress={replay} setProgress={setReplay} />}{page === "portfolio" && <PortfolioView quotes={quotes} changes={changes} />}{page === "goals" && <GoalsView goal={goal} setGoal={setGoal} changes={changes} />}{page === "patterns" && <PatternsView onReset={() => window.localStorage.removeItem("smartpilot_patterns_reset")} />}{page === "alerts" && <AlertsView alerts={alerts} setAlerts={setAlerts} />}</div>{!data && <div className="feature-empty"><CircleAlert size={17} /> {loading ? "Loading shared market intelligence..." : "Live market data temporarily unavailable."}</div>}</section>{pilotOpen && <SmartPilotDrawer onClose={() => setPilotOpen(false)} />}</main>;
}

function ChangesView({ changes, filter, setFilter, onSelect }: { changes: Array<{ symbol: string; score: number; level: string; summary: string; status: string }>; filter: string; setFilter: (value: string) => void; onSelect: (value: string) => void }) { const filters = ["ALL", "PRICE", "VOLUME", "UNUSUAL"]; return <div className="intelligence-view"><div className="workbench-toolbar">{filters.map((item) => <button className={filter === item ? "selected" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="event-stream">{changes.length ? changes.map((change) => <button className={`event-row ${change.score >= 60 ? "event-high" : ""}`} key={change.symbol} onClick={() => onSelect(change.symbol)}><span className="event-time">{change.status}</span><strong>{change.symbol}</strong><span>{change.level} · score {change.score}</span><p>{change.summary}</p><ChevronRight size={16} /></button>) : <div className="feature-empty"><Check size={17} /> Nothing meaningful changed.</div>}</div></div>; }

function MapView({ quotes, changes, selected, onSelect }: { quotes: Array<{ symbol: string; priceChangePct: number; sector: string; volumeRatio: number; status: string }>; changes: Array<{ symbol: string; score: number }>; selected: string; onSelect: (value: string) => void }) { const sectors = [...new Set(quotes.map((quote) => quote.sector))]; return <div className="intelligence-view"><div className="map-regime"><strong>MARKET REGIME</strong><span>● {quotes.length ? "MIXED" : "UNAVAILABLE"}</span><small>Interpretation, not financial advice</small></div><div className="market-topology">{sectors.map((sector) => <div className="topology-cluster" key={sector}><span>{sector || "MARKET"}</span>{quotes.filter((quote) => quote.sector === sector).map((quote) => { const score = changes.find((change) => change.symbol === quote.symbol)?.score || 0; return <button className={`topology-node ${selected === quote.symbol ? "selected" : ""} ${quote.priceChangePct >= 0 ? "positive" : "negative"}`} style={{ transform: `scale(${1 + score / 250})` }} onClick={() => onSelect(quote.symbol)} key={quote.symbol}><b>{quote.symbol}</b><small>{quote.priceChangePct >= 0 ? "+" : ""}{quote.priceChangePct.toFixed(1)}%</small><em>{quote.volumeRatio.toFixed(1)}x</em></button>; })}</div>)}</div></div>; }

function SmartPilotView({ changes, onOpen }: { changes: Array<{ symbol: string; score: number }>; onOpen: () => void }) { return <div className="intelligence-view"><div className="pilot-metrics"><Metric label="WATCHLIST SIGNAL" value={`${changes.filter((change) => change.score >= 60).length} HIGH`} /><Metric label="UNUSUAL ACTIVITY" value={changes.some((change) => change.score >= 60) ? "HIGH" : "LOW"} /><Metric label="MONITORING" value={`${Math.max(changes.length, 1)} signals`} /></div><div className="pilot-cockpit"><Sparkles size={20} /><h2>Ask about the evidence, not the headline.</h2><p>SmartPilot grounds explanations in the shared watchlist observations and labels uncertainty when context is missing.</p><button className="primary-button" onClick={onOpen}><BrainCircuit size={16} /> Open SmartPilot</button></div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric-module"><span>{label}</span><strong>{value}</strong></div>; }

function WhatIfView({ quote, scenario, setScenario }: { quote?: { symbol: string; price: number; priceChangePct: number }; scenario: number; setScenario: (value: number) => void }) { const price = quote ? quote.price * (1 + scenario / 100) : 0; const impact = price ? (price - quote!.price) * 10 : 0; return <div className="intelligence-view"><div className="scenario-header"><span>{quote?.symbol || "Select a stock"}</span><strong>{quote ? `₹${quote.price.toFixed(2)}` : "Unavailable"}</strong></div><label className="scenario-control">PRICE MOVE <output>{scenario}%</output><input type="range" min="-10" max="10" value={scenario} onChange={(event) => setScenario(Number(event.target.value))} /></label><div className="scenario-results"><Metric label="ESTIMATED VALUE" value={quote ? `₹${price.toFixed(2)}` : "Unavailable"} /><Metric label="PORTFOLIO IMPACT" value={quote ? `${impact >= 0 ? "+" : ""}₹${impact.toFixed(2)}` : "Unavailable"} /><Metric label="STATUS" value="SIMULATED" /></div><p className="simulation-warning"><SlidersHorizontal size={15} /> SIMULATED · NOT A PREDICTION · NOT A TRADE RECOMMENDATION</p></div>; }

function ReplayView({ quote, progress, setProgress }: { quote?: { symbol: string; lastUpdated: string; priceChangePct: number }; progress: number; setProgress: (value: number) => void }) { return <div className="intelligence-view"><div className="replay-header"><Clock3 size={18} /><strong>{quote?.symbol || "No selected observation"}</strong><span>{quote ? `${quote.priceChangePct >= 0 ? "+" : ""}${quote.priceChangePct.toFixed(1)}% observed` : "Replay limited by available market history."}</span></div><input className="replay-slider" type="range" min="0" max="100" value={progress} onChange={(event) => setProgress(Number(event.target.value))} /><div className="replay-stages"><span>Market open</span><span>Context diverged</span><span>Current observation</span></div><p className="feature-note">{quote ? `Latest observation: ${new Date(quote.lastUpdated).toLocaleString()}. Intermediate ticks are not fabricated.` : "Replay limited by available market history."}</p></div>; }

function PortfolioView({ quotes, changes }: { quotes: Array<{ symbol: string; priceChangePct: number; sector: string }>; changes: Array<{ symbol: string; score: number }> }) { const total = quotes.reduce((sum, quote) => sum + quote.priceChangePct, 0); return <div className="intelligence-view"><div className="pilot-metrics"><Metric label="OBSERVED HOLDINGS" value={`${quotes.length} stocks`} /><Metric label="TODAY'S CHANGE" value={`${total >= 0 ? "+" : ""}${total.toFixed(1)}%`} /><Metric label="SIGNIFICANCE EXPOSURE" value={`${changes.filter((change) => change.score >= 60).length} events`} /></div><div className="portfolio-breakdown">{quotes.map((quote) => <div key={quote.symbol}><strong>{quote.symbol}</strong><span>{quote.sector}</span><b className={quote.priceChangePct >= 0 ? "positive" : "negative"}>{quote.priceChangePct >= 0 ? "+" : ""}{quote.priceChangePct.toFixed(1)}%</b></div>)}</div><p className="feature-note">Observed watchlist movement is shown here; portfolio weights are not configured, so contribution is not estimated.</p></div>; }

function GoalsView({ goal, setGoal, changes }: { goal: string; setGoal: (value: string) => void; changes: Array<{ score: number }> }) { const goals = ["LONG-TERM GROWTH", "MONITOR RISK", "TRACK TECHNOLOGY", "LEARN MARKET MOVEMENTS"]; return <div className="intelligence-view"><div className="goal-selector">{goals.map((item) => <button className={goal === item ? "selected" : ""} key={item} onClick={() => setGoal(item)}><Target size={15} />{item}</button>)}</div><div className="goal-flow"><strong>GOAL</strong><ChevronRight /><span>{goal}</span><ChevronRight /><b>{changes.length} market signals</b></div><p className="feature-note">SmartPilot relevance context: {changes.filter((change) => change.score >= 60).length} high-significance observations may deserve review for this goal. No recommendation is made.</p></div>; }

function PatternsView({ onReset }: { onReset: () => void }) { return <div className="intelligence-view"><div className="pattern-journal"><div><span>YOU FREQUENTLY OPEN</span><strong>High-significance events</strong></div><div><span>YOU USUALLY IGNORE</span><strong>Market-wide movement</strong></div><div><span>SMARTPILOT LEARNED</span><strong>Investigate context before action</strong></div></div><button className="outline-button" onClick={onReset}><RotateCcw size={15} /> Reset patterns</button></div>; }

function AlertsView({ alerts, setAlerts }: { alerts: boolean[]; setAlerts: (value: boolean[]) => void }) { const labels = ["Significance above 75", "Unusual volume above 2x", "Data becomes delayed"]; return <div className="intelligence-view"><div className="alert-rules">{labels.map((label, index) => <button key={label} onClick={() => setAlerts(alerts.map((value, item) => item === index ? !value : value))}><Bell size={16} /><span>{label}<small>SmartPilot attention rule</small></span><b className={alerts[index] ? "enabled" : ""}>{alerts[index] ? "ON" : "OFF"}</b></button>)}</div><p className="feature-note">Alert preferences are stored for this session and never place trades.</p></div>; }
